//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizarraDeVuelo.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int idReservas { get; set; }
        public string aeronave { get; set; }
        public Nullable<int> piloto { get; set; }
        public string disponibilidad { get; set; }
        public string mision { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora_reserva { get; set; }
    
        public virtual Areonave Areonave { get; set; }
        public virtual Piloto Piloto1 { get; set; }
    }
}
