//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizarraDeVuelo.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public int idVuelo { get; set; }
        public string aeronave { get; set; }
        public Nullable<int> piloto { get; set; }
        public string mision { get; set; }
        public string desde { get; set; }
        public string hasta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
        public Nullable<System.TimeSpan> hora_llegada { get; set; }
        public string Observacion { get; set; }
        public string plan_vuelo { get; set; }
        public Nullable<int> Combustible { get; set; }
        public string comb_medida { get; set; }
    
        public virtual Areonave Areonave { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Localidad Localidad1 { get; set; }
        public virtual Mision Mision1 { get; set; }
        public virtual Piloto Piloto1 { get; set; }
    }
}
